spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: '*'
            allowed-headers: '*'
            allowed-methods: '*'
            allow-credentials: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
            - JwtAuthenticationFilter
        - id: post-service-secured
          uri: lb://post-service
          predicates:
            - Path=/api/posts/**
          filters:
            - StripPrefix=2
            - JwtAuthenticationFilter
        - id: post-service-public
          uri: lb://post-service
          predicates:
            - Path=/api/public/posts/**
          filters:
            - RewritePath=/api/public/posts(?<segment>/?.*), /public$\{segment}
      discovery:
        locator:
          enabled: false
  codec:
    log-request-details: true

logging:
  level:
    web: debug
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
    reactor.netty.http.client: DEBUG

debug: true

server:
  port: 8080
  address: 0.0.0.0
eureka:
  client:
    service-url:
      defaultZone: http://${SPRING_EUREKA_DEFAULT_ZONE:localhost}:8761/eureka/

#
#springdoc:
#  api-docs:
#    enabled: true
#    path: /v3/api-docs
#  swagger-ui:
#    enabled: true
#    config-url: /v3/api-docs/swagger-config
#    urls:
#      - name: gateway-service
#        url: /v3/api-docs
